# Generated by Django 5.2.15 on 2026-07-18 10:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Employee', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='EMP001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.date(2026, 7, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
