# Generated by Django 5.2.15 on 2026-08-23 09:11

import django.db.models.deletion
from django.db import migrations, models


def populated_department_fk(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    Department = apps.get_model("departments", "Department")

    for employee in Employee.objects.all():
        department = Department.objects.get(
            name=employee.department
        )

        employee.department_fk = department
        employee.save(update_fields=["department_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_populate_departments'),
        ('employees', '0002_employee_created_at_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_temp', to='departments.department'),
        ),

        migrations.RunPython(
            populated_department_fk,
        ),
    ]
