# Generated by Django 5.2.15 on 2026-08-24 07:48

import django.db.models.deletion
from django.db import migrations, models


def copy_department_relationship(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")

    for employee in Employee.objects.all():
        employee.department_new_id = employee.department_fk_id
        employee.save(update_fields=["department_new"])


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_populate_departments'),
        ('employees', '0003_employee_department_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_new',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='employees_new', to='departments.department',
                null=True
            ),
        ),

        migrations.RunPython(
            copy_department_relationship,
        ),

        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        
        migrations.RemoveField(
            model_name='employee',
            name='department_fk',
        ),

        migrations.RenameField(
            model_name="employee",
            old_name="department_new",
            new_name="department",
        ),

        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="departments.department",
            ),
        ),
    ]
