# Generated by Django 5.2.15 on 2026-08-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_department_fk_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operations', to='employees.employee'),
        ),
    ]
