# Generated by Django 5.2.15 on 2026-08-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_populate_departments'),
        ('employees', '0004_remove_employee_department_fk_and_more'),
        ('operations', '0002_alter_operations_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
    ]
