# Generated by Django 5.2.15 on 2026-08-23 07:35

from django.db import migrations


def create_departments(apps, schema_editor):
    Department = apps.get_model("departments", "Department")

    department_name = [
        "Finance",
        "Sales",
        "HR",
        "Engineering",
    ]

    for name in department_name:
        Department.objects.create(
            name=name,
            description=f"{name} Department",
        )


def  delete_departments(apps, schema_editor):
    Department = apps.get_model("departments", "Department")

    Department.objects.filter(
        name__in=[
            "Finance",
            "Sales",
            "HR",
            "Engineering",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name'),
    ]

    operations = [
        migrations.RunPython(
            create_departments,
            delete_departments,
        ),
    ]
